// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Candidate interface {
	IsCandidate()
}

type Committee interface {
	IsCommittee()
}

type Pac interface {
	IsPac()
}

type IdentificationNumber struct {
	ID string `json:"_id"`
}

func (IdentificationNumber) IsCandidate() {}
func (IdentificationNumber) IsPac()       {}
func (IdentificationNumber) IsCommittee() {}

type IndividualContributor struct {
	ID        string `json:"_id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	State     bool   `json:"state"`
	ZipCode   *int   `json:"zipCode"`
}

type MinimumMetadata struct {
	LastName    string `json:"lastName"`
	Affiliation string `json:"affiliation"`
}

func (MinimumMetadata) IsCandidate() {}
func (MinimumMetadata) IsPac()       {}
func (MinimumMetadata) IsCommittee() {}

type NewIndividualContributor struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	State     bool   `json:"state"`
	ZipCode   *int   `json:"zipCode"`
}
